### ISSUE TITLE
Ephemeral Runners?

### ISSUE THREAD

**Issue by HenryNguyen5** [philips-labs/terraform-aws-github-runner#182] opened 2020-09-01 02:01 UTC
## Problem to solve
As a developer interacting with a public repository, I want to be able to have ephemeral instances so that I can safely use self-hosted runners in a public repo.

## Intended users
Any public repository user where github actions are used, and the default github hosted runners do not provide sufficient resources.

## Proposal
- Have a warm pool of idling runners waiting for a job from github (polling sqs queue or something)
- When a idling runner gets a job, execute that job, and delete the runner when finished (the lifetime of the runner is the same as the GHA job it is executing)

## What does success look like, and how can we measure that?
- Jobs are quickly executed since runners are pre-provisioned
- Security concerns over persistence of data across jobs are addressed since the lifetime of runners are tied to a single github job.

**Comment by npalm** [comment] 2020-09-02 06:56
Thanks for creating the suggestion, and I really support this idea. Any idea for iimplementation. There are potential some caveats:
- Not every event that we recieve from GitHub is matching 1-1 with a job. So that part needs then more adjustment.
- Not easy, but possible to detect that a job is finish, requires maybe a small agent on the host.
- Having hot instances only requires to configure the runner at the moment a job should start, a command via a SSM document seems a logical choice.

**Comment by directionless** [comment] 2021-02-24 04:12
For similar reasons to the OP, this is a feature I also like. A related project, [envoyproxy/ci-infra](https://github.com/envoyproxy/ci-infra) does this by having the runners in an ASG, and detaching on job start.

**Comment by mrmeyers99** [comment] 2021-06-16 19:43
Upvoting this as well

**Comment by npalm** [comment] 2021-06-16 21:52
Would be great if we can support this strategy as well. Really like the idee. Hope I have the next months some time to do some experiments!

**Comment by mrmeyers99** [comment] 2021-07-14 17:22
It looks like there is a `--once` flag you can pass to the runner on startup but it's not officially supported yet and apparently has some issues.  https://github.com/actions/runner/issues/510. Maybe the best solution is to wait for this to be officially supported?

**Comment by npalm** [comment] 2021-07-14 18:51
GitHub is also started with testing an event for workflow jobs to handle a better sclaing

**Comment by uilton-oliveira** [comment] 2021-09-15 01:14
It looks like that the support for ephemeral was finally merged on https://github.com/actions/runner/pull/660
Would be nice to have support here aswell for a better scale-up/down...

**Comment by aidan-mundy** [comment] 2021-09-17 00:22
It isn't clear whether or not the new `--ephemeral` flag is supported for GHES. Regardless, I see this as an essential tool, and would love to see it included here.

**Comment by gertjanmaas** [comment] 2021-09-20 07:27
is there anyone that can test the ephemeral flag with GHES?

**Comment by aidan-mundy** [comment] 2021-09-20 22:34
It has been confirmed in https://github.com/actions/runner/pull/660 that `--ephemeral` is not yet supported on GHES

**Comment by jensenbox** [comment] 2021-09-21 05:27
What changes are required to implement this? I understand that it is not available for GHES but in other environments this would be amazing. https://docs.github.com/en/actions/hosting-your-own-runners/autoscaling-with-self-hosted-runners

**Comment by gertjanmaas** [comment] 2021-09-21 08:15
From the top of my head:
1. Add the `--ephemeral` flag to the code that installs the runner on the EC2 instance
2. Figure out a way to terminate the EC2 instance after the runner is done
3. Implement new scaling logic for ephemeral runners, because the current logic will probably not work (e.g. the idle configuration)
4. TEST! 😄 

Of course all of this needs to be configurable and backwards compatible for GHES.

**Comment by mrmeyers99** [comment] 2021-09-21 11:39
It would be nice if the idle configuration meant how many runners should be registered and waiting for jobs. Every time one getsa job, the scale up lambda would register another.

**Comment by uilton-oliveira** [comment] 2021-09-21 14:08
https://github.com/actions/runner/pull/660#issuecomment-924006410

--ephemeral will ship in the next version of GHES (but as I said above it requires server changes to fix the race condition with client side only assignment)

**Comment by ScottGuymer** [comment] 2021-12-02 19:33
Implementing this is in progress. Closing this in favour of #1372. Will track the implementation of this there.

**Closed by ScottGuymer** 2021-12-02 19:33 UTC
Labels: enhancement, help wanted
