### ISSUE TITLE
Hitting rate limits because ssm calls in runners.ts are not staggered or spread out

### ISSUE THREAD

**Issue by devshah1** [philips-labs/terraform-aws-github-runner#1841] opened 2022-03-10 20:01 UTC
**Issue**
We ran into rate limits yesterday when the pool configuration adjusts the size of EC2 instances by scaling up.

After digging into the code, I saw that the calls to the [ssm `putParameter`](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/lambdas/runners/src/aws/runners.ts#L205) method are not staggered or spread out in `runners.ts`.  

Concurrent calls to this method triggers the rate limits since the parameter store only allows 40 requests per second by default.

**How to reproduce?**
If the pool adjusts more than 40 instances at a time, you'll see throttling errors from the AWS SDK.

**Proposed resolution**
Use waits to stagger calls to the ssm parameter store in the specified file.

**Root cause file reference**:
https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/lambdas/runners/src/aws/runners.ts#L205

**Comment by devsh4** [comment] 2022-03-12 05:27
@npalm I added a fix for this, please review the PR.

**Comment by npalm** [comment] 2022-03-12 09:29
According this AWS docs the rate limit should be 100 per second for non mutating and 200 for mutation API calls. Several other API calles are done before parameters are writeen, and as well other lamba's can consume from the same bucket for API rate limits. 

Also during the boot process the instances is retrieving via API calls config via SSM. Those could potential have the same issue. By introducing a delay we should keep in mind that parameters should be created before the instances starts retrieving them. Typically at leas 25 seconds. Furthemore the Lambda have default time out. So that should match as well.

in PR #1843 a wait of 25 ms is introduced after each call. Which limits the put parameter to call no more than 40 times the API in a second. Sound to me reasonable. 

@devshah1 can you test the PR?

**Comment by devsh4** [comment] 2022-03-12 18:26
@npalm As far as the rate limit for AWS goes I confirmed with the AWS team that the current rate limit was 100 req/s and this is after increasing the throughput for our account. 

Good point about the other calls that happen underneath however I monitored the behavior extensively for our workloads and whenever the pool topped up > 50 EC2 instances (this number changed to 100 once we increased the throughput), the SSM calls met with throttling which means the parameters weren't added to the store and thus EC2 instances couldn't fetch the parameters from SSM on boot. This led to a scenario where we had 2-3x EC2 instances but only half of them got registered successfully as GH runners.

I'll test out the changes in PR #1843 with production level workloads and get back with the results.

_(Sorry for posting from 2 accounts, I opened the issue with my work account)_

**Comment by devsh4** [comment] 2022-03-12 20:20
@npalm Weirdly getting the below error when the ec2 instance is deleting the ssm parameter during boot, however it is able to fetch the parameters successfully - 

`An error occurred (ParameterNotFound) when calling the DeleteParameter operation`

Would you know why this could happen?

**Comment by devsh4** [comment] 2022-03-12 21:37
I figured out what was happening with the deletion error, the `start-runner.sh` [doesn't have a thorough check](https://github.com/philips-labs/terraform-aws-github-runner/blob/develop/modules/runners/templates/start-runner.sh#L42) to ensure that the parameter was retrieved successfully. This is the reason deletion fails with `ParameterNotFound` error because it was never created and thus never retrieved.

**Comment by devsh4** [comment] 2022-03-13 01:09
@npalm I updated the fix to be simpler as passing the call in `setTimeout` wasn't working as intended.

I tested this with production level workload where each time the pool adjust function starts from 0 & goes up till `n`. The fix works perfectly end to end without hitting the rate limits.

**Test scenarios with varying pool size**:

1. Pool size: 5 runners
2. Pool size: 5 runners
3. Pool size: 5 runners
4. Pool size: 5 runners

1. Pool size: 5 runners


1. Pool size: 5 runners

**Closed** 2022-04-13 14:10 UTC
Labels: bug, help wanted

**Comment by devsh4** [comment] 2022-08-02 16:09
@npalm Can you please reopen this issue? I am working on reopening the original PR. Thanks!

**Comment by devsh4** [comment] 2022-08-02 16:55
@npalm Please review when you have time and check the [related PR](https://github.com/philips-labs/terraform-aws-github-runner/pull/1843) I had opened a couple months ago for more context.

**Comment by npalm** [comment] 2022-08-02 17:17
@devsh4 can you re-open the PR, or recreate. It is closed and needs to re-based

**Comment by devsh4** [comment] 2022-08-02 17:36
@npalm I have opened a new PR, check the [latest comment](https://github.com/philips-labs/terraform-aws-github-runner/issues/1841#issuecomment-1202986126).
https://github.com/philips-labs/terraform-aws-github-runner/pull/2305
