### ISSUE TITLE
Job stays queued if triggered when no runners are available

### ISSUE THREAD

**Issue by nafpliot** [philips-labs/terraform-aws-github-runner#458] opened 2021-01-14 16:10 UTC
I think this is related to issue https://github.com/philips-labs/terraform-aws-github-runner/issues/74 . I have exactly the same problem.

In short: I trigger a new job when there are no available runners, scale-up lambda gets triggered and spawns an instance, installation of the runner is done successfully - I see the runner idle in the UI -. The job doesn't get picked by the runner and stays queued forever. If in the meantime I trigger a new job while this runner is active, it works.

Is there anything I can try? I thought this problem was solved. Thank you!

**Comment by anafpliot** [comment] 2021-01-15 16:40
Some more info. I don't know if it's normal or related to the problem.

It seems that the runner gets this warning 
`[2021-01-15 16:25:37Z WARN GitHubActionsService] Authentication failed with status code 401.` 

However, the setup finishes fine after that
`[2021-01-15 16:25:33Z INFO Listener] Runner execution has finished with return code 0`

When I start the second job (while the runner is already active), the authentication warning seems to be gone.

**Comment by nafpliot** [comment] 2021-01-15 16:41
Some more info. I don't know if it's normal or related to the problem.

It seems that the runner gets this warning 
`[2021-01-15 16:25:37Z WARN GitHubActionsService] Authentication failed with status code 401.` 

However, the setup finishes fine after that
`[2021-01-15 16:25:33Z INFO Listener] Runner execution has finished with return code 0`

When I start the second job (while the runner is already active), the authentication warning seems to be gone.

**Comment by npalm** [comment] 2021-01-16 09:55
@nafpliot jobs stays queued we have seen several time in the past. It was always related to an new version of the github runner action distribution. Not sure if the issue is back. We haven't seen problems last week. But on the date you raised the issue GitHub released a new version of the runner. So I guess the proble is related again to this upgrade. 

I will check next week our logs for the warning you menation.

**Comment by npalm** [comment] 2021-01-20 20:41
@nafpliot I see the same logline, but after the WARN the runner seems to continue as normal. Thanks for having a look, but seems more an issue to the github runners. I close the issue, feel free to re-open if needed.

**Closed by npalm** 2021-01-20 20:41 UTC
