### ISSUE TITLE
UserData  stuck Waiting for configuration in UserData

### ISSUE THREAD

**Issue by Srikanth1992** [philips-labs/terraform-aws-github-runner#1131] opened 2021-08-24 02:09 UTC
I'm trying to deploy terraform-aws-github-runner on Amzon Linux 2.

I have updated the UserData as below: 

#!/bin/bash -e
exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1
/root/.deploy.sh
yum update -y

##yum install amazon-cloudwatch-agent -y
#amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:github-runner-poc-cloudwatch_agent_config_runner
#
# Install docker
amazon-linux-extras install docker
service docker start
usermod -a -G docker ec2-user

yum install -y curl jq git

USER_NAME=ec2-user
cd /home/$USER_NAME
mkdir actions-runner && cd actions-runner

aws s3 cp s3://github-runner-poc-dist-vncz2ej5qd6pr5pnydv3f4yv/actions-runner-linux.tar.gz actions-runner.tar.gz
tar xzf ./actions-runner.tar.gz
rm -rf actions-runner.tar.gz

INSTANCE_ID=$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-id)
REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)

echo wait for configuration
while [[ $(aws ssm get-parameters --names github-runner-poc-$INSTANCE_ID --with-decryption --region $REGION | jq -r ".Parameters | .[0] | .Value") == null ]]; do
    echo Waiting for configuration ...
    sleep 1
done
CONFIG=$(aws ssm get-parameters --names github-runner-poc-$INSTANCE_ID --with-decryption --region $REGION | jq -r ".Parameters | .[0] | .Value")
aws ssm delete-parameter --name github-runner-poc-$INSTANCE_ID --region $REGION

export RUNNER_ALLOW_RUNASROOT=1
os_id=$(awk -F= '/^ID/{print $2}' /etc/os-release)
if [[ "$os_id" =~ ^amzn* ]]; then
    ./bin/installdependencies.sh
fi

./config.sh --unattended --name $INSTANCE_ID --work "_work" $CONFIG
  
chown -R $USER_NAME:$USER_NAME .
OVERWRITE_SERVICE_USER= ${run_as_root_user}
SERVICE_USER=${OVERWRITE_SERVICE_USER:-$USER_NAME}

./svc.sh install $SERVICE_USER

./svc.sh start

My server /etc/os-releases has this entries.
"amzn" "centos rhel fedora"

I'm confused what this is doing here

```
while [[ $(aws ssm get-parameters --names github-runner-poc-$INSTANCE_ID --with-decryption --region $REGION | jq -r ".Parameters | .[0] | .Value") == null ]]; do
    echo Waiting for configuration ...
    sleep 1
done
CONFIG=$(aws ssm get-parameters --names github-runner-poc-$INSTANCE_ID --with-decryption --region $REGION | jq -r ".Parameters | .[0] | .Value")
aws ssm delete-parameter --name github-runner-poc-$INSTANCE_ID --region $REGION

export RUNNER_ALLOW_RUNASROOT=1
os_id=$(awk -F= '/^ID/{print $2}' /etc/os-release)
if [[ "$os_id" =~ ^amzn* ]]; then
    ./bin/installdependencies.sh
fi

```

My instance doesn't have any parameters to get the while loop working.

Let me know if you need more information

Thanks,

**Comment by npalm** [comment] 2021-09-30 15:31
@Srikanth1992 can we close this issue?

**Comment by npalm** [comment] 2021-12-03 17:52
Due to inactivity, I will close the issue. And assume the issue is resolved. Thanks for reaching out, and feel free to re-open if needed.

**Closed by npalm** 2021-12-03 17:52 UTC
Labels: question
